import { NextPage } from "next";
import Head from "next/head";

const Test: NextPage = () => {
    return(
        <>
        <Head>
            <title>Test Page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Test</h1>
        </>
    )
}

export default Test;