import type { GetServerSideProps } from 'next';
import Head from 'next/head';
import Header from '../components/header/Header';
import components from '../styles/Home.module.css';
import checkUser, { UserData } from '../scripts/checkUser';
import { CurrentTheme } from '../components/themechanger/ThemeChanger';
import { ChangeVarProp } from '../components/customTheme/CustomTheme';

export const getServerSideProps: GetServerSideProps = async (context) => {
  const checkedUser = await checkUser(context);
  if (checkedUser.error || !checkedUser.data) {
    return {
      props: {
        loggedIn: false
      }
    }
  }
  return {
    props: {
      data: checkedUser.data,
      loggedIn: true
    }
  }
}

const Home = ({data, loggedIn, changeTheme, currentTheme, changeVar }: { data?: UserData, loggedIn: boolean, changeTheme: any, currentTheme: CurrentTheme, changeVar: ChangeVarProp}) => {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dashboard.png" />
      </Head>
      <Header loggedIn={loggedIn} where='home' changeTheme={changeTheme} currentTheme={currentTheme} changeVar={changeVar}>Dashboard</Header>
      <main className={components.main}>
        <h1 className={components.greeting}>Hello <span className={components.fancy}>{data ? data.usersRName : "Guest"}</span></h1>
      </main>
    </>
  );
}

export default Home;
