import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello</h1>
      <Link href="/search?query=test">Test</Link>
    </>
  )
}

export default Home
